language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "scrappycocco-github"

cache:
  directories:
    - '$HOME/.sonar/cache'

script:
  - mvn package install
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn sonar:sonar -Dsonar.projectKey=ScrappyCocco_PlanetCoasterXMLMerge -Dsonar.organization=scrappycocco-github -Dsonar.host.url=https://sonarcloud.io
